os: linux
language: node_js
node_js:
  - "4"
  - "6"
sudo: true
#after_success: npm run coverage
env:
  - MONGODB_VERSION=2.4.x
  - MONGODB_VERSION=2.6.x
  - MONGODB_VERSION=3.0.x
  - MONGODB_VERSION=3.2.x
  - MONGODB_VERSION=3.4.x
  - MONGODB_VERSION=3.6.x
